{{- if (.Values.externalSecret) }}
{{- range $nameSuffix, $data := .Values.externalSecret.files }}
---
{{- if $.Capabilities.APIVersions.Has "external-secrets.io/v1/ExternalSecret" }}
apiVersion: external-secrets.io/v1
{{- else }}
apiVersion: external-secrets.io/v1beta1
{{- end }}
kind: ExternalSecret
metadata:
  name: external-secret-{{ template "robustName" $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "helm-chart.labels" $ | nindent 4 }}
{{- if $.Values.externalSecret.additionalLabels }}
{{ toYaml $.Values.externalSecret.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.externalSecret.annotations }}
  annotations:
{{ toYaml $.Values.externalSecret.annotations | indent 4 }}
{{- end }}
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
{{- if and (not $data.data) (not $data.dataFrom) }}
{{- fail "Data or datafrom not specified for secret {{ template 'robustName' $.Release.Name }}-{{ $nameSuffix }} " }}
{{- end }}
{{- if $data.data }}
  data:
{{- range $secretKey, $remoteRef := $data.data}}
    - secretKey: {{ $secretKey }}
{{ toYaml $remoteRef | indent 6}}
{{- end }}
{{- end }}
{{- if $data.dataFrom }}
  dataFrom:
{{- if kindIs "slice" $data.dataFrom }}
{{- range $data.dataFrom }}
  - extract:
      key: {{ . }}
{{- end }}
{{- else }}
  - extract:
{{ toYaml $data.dataFrom | indent 6  }}
{{- end }}
{{- end }}
  secretStoreRef:
    name: {{ default $.Values.externalSecret.secretStore.name ($data.secretStore).name }}
    kind: {{ default $.Values.externalSecret.secretStore.kind ($data.secretStore).kind }}
  target:
    name: {{ $nameSuffix }}
    template:
      type: {{ $data.type | default "Opaque" }}
{{- if or $data.annotations $data.labels}}
      metadata:
{{- if $data.annotations }}
        annotations:
{{ toYaml $data.annotations | indent 10 }}
{{- end }}
{{- if $data.labels }}
        labels:
{{ toYaml $data.labels | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}