{{- if and .Values.rbac .Values.rbac.serviceAccount .Values.rbac.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "robustName" .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  {{- with .Values.rbac.serviceAccount.additionalLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}